packages:
  - packages/**
  - projects/**

catalog:
  "@biomejs/biome": latest
  "@hono/node-server": latest
  "@hono/vite-build": latest
  "@hono/vite-dev-server": latest
  "@hono/zod-validator": latest
  "@nuxt/test-utils": latest
  "@playwright/test": latest
  "@types/node": latest
  "@types/react": latest
  "@types/react-dom": latest
  "@vitejs/plugin-react-swc": latest
  "@vitejs/plugin-vue": latest
  "@vue/test-utils": latest
  happy-dom: latest
  hono: latest
  honox: latest
  nuxt: latest
  react: latest
  react-dom: latest
  react-router-dom: latest
  styled-components: latest
  typescript: latest
  vite: latest
  vitest: latest
  vue: latest
  vue-router: latest
  vue-tsc: latest
  zod: latest
